# basic options
title: Boris Fouotsa
author: Tako Boris Fouotsa
email: tako dot fouotsa at epfl dot ch
twitter_username: FouotsaB
github_username: BorisFouotsa




# Build settings
markdown: kramdown
theme: minima

pages:
  - Home: index.md
  - Research work: index_2_research.md
  - Academic activities: index_3_academicActivities.md
  - Events: index_4_events.md
  - Other: index_5_other.md
  - Africacrypt 2024: index111.md
