# basic options
title: Boris Fouotsa
author: Tako Boris Fouotsa
email: takoboris.fouotsa@uniroma3.it
twitter_username: FouotsaB
github_username: BorisFouotsa




# Build settings
markdown: kramdown
theme: minima
$background-color: #1d1d1d; /* a dark, off-black for the bg */
