# basic options
#title: Boris Fouotsa
author: Boris Fouotsa
email: fouotsabcrb@gamail.com
description: A wonderful site
twitter_username: FouotsaB
github_username: BorisFouotsa

# Build settings
markdown: kramdown
theme: minima
