# basic options
title: Boris Fouotsa
author: Tako Boris Fouotsa
email: tako dot fouotsa at epfl dot ch
twitter_username: FouotsaB
mastodon_username: FouotsaB
github_username: BorisFouotsa




# Build settings
markdown: kramdown
theme: minima
