# basic options
title: Boris Fouotsa
author: Tako Boris Fouotsa
email: tako.fouotsa@epfl.ch
twitter_username: FouotsaB
github_username: BorisFouotsa




# Build settings
markdown: kramdown
theme: minima
