# basic options
title: Boris Fouotsa
author: Boris Fouotsa
email: takoboris.fouotsa@uniroma3.it
description:
twitter_username: FouotsaB
github_username: BorisFouotsa
orcid: 0000-0003-1821-8406

# Build settings
markdown: kramdown
theme: minima
