# basic options
title: Boris Fouotsa
author: Boris Fouotsa
email: takoboris.fouotsa@uniroma3.it
twitter_username: FouotsaB
github_username: BorisFouotsa
orcid_username: 0000-0003-1821-8406
linkedin_username: tako-boris-fouotsa-799737118


# Build settings
markdown: kramdown
theme: minima
