# basic options
title: Boris Fouotsa
author: Tako Boris Fouotsa
email: takoboris.fouotsa@uniroma3.it
twitter_username: FouotsaB
github_username: BorisFouotsa




# Build settings
markdown: kramdown
theme: minima
