site_name: BorisFouotsa
site_url: https://borisfouotsa.com/

nav:
  - Home: index.md
  - Research work: index_2_research.md
  - Academic activities: index_3_academicActivities.md
  - Events: index_4_events.md
  - Other: index_5_other.md
  - Africacrypt 2024: index111.md

